
services:
  pgsql:
    image: timescale/timescaledb-ha:pg17
    container_name: iotsharp-dev-pgsql
    volumes:
      - "./data/postgresql:/var/lib/postgresql"
    environment:
      TZ: "Asia/Shanghai"
      POSTGRES_USER: postgres
      POSTGRES_DB: IoTSharp
      POSTGRES_PASSWORD: BrrveCFVAZ6kM6vhjFMd 
    ports: 
     - "5432:5432"
    networks:
      - iotsharp-network
 
  rabbitmq:
    image: rabbitmq:4-management-alpine
    container_name: iotsharp-dev-rabbitmq
    hostname: rabbitmq
    environment:
      TZ: "Asia/Shanghai"
      RABBITMQ_DEFAULT_USER: iotsharp
      RABBITMQ_DEFAULT_PASS: BrrveCFVAZ6kM6vhjFMd
    volumes:
      - "./data/rabbitmq:/var/lib/rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - iotsharp-network



networks: 
  iotsharp-network:
      driver:  bridge
